chat/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
# from .views import (
# 	chat,
# )

app_name = 'chat'
urlpatterns =[
	
	#url(r'$',chat, name='chat'),
	url(r'^ChatPage/$',views.ChatPage, name='chatpage'),
	url(r'^post/$',views.Post, name='post'),
    url(r'^messages/$',views.Messages, name='messages'),
	
]

dataadd/urls.py
from django.conf.urls import url
from django.contrib import admin
from el_pagination.decorators import page_template

from .views import (
	doctor_article_list,
	doctor_article_create,
	doctor_article_detail,
	doctor_article_update,
	doctor_article_delete,
	myarticle,
	article,
	friends,
	connect,
	connectrequest,
	entry_list,
)

app_name = 'dataadd'
urlpatterns =[
	
	#url(r'$',"dataadd.views.complain_create", name='complain'),
	#url(r'$',complain_list, name='complain_list'),
	url(r'connect/(?P<operation>.+)/(?P<pk>\d+)/$',connect,name='connect'),
	url(r'connectrequest/(?P<operation>.+)/(?P<pk>\d+)/$',connectrequest,name='connectrequest'),
	url(r'friends/$',friends,name='friends'),
	url(r'^article/$',article, name='article'),
	url(r'^myarticles/$',myarticle, name='myarticle'),#name ide u html brackete kod hrefa
	url(r'^create/$',doctor_article_create,name='complain'), 
	url(r'^pagin/$',
        page_template('service_list_pag.html')(entry_list), # here is object list 
        {'template': 'test_pag.html'},# here is  called upper  object list template  
        name='pagin'),
	#url(r'^detail/(?P<id>\d+)/$',complain_detail),
	#url(r'^(?P<id>\d+)/$',complain_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/$',doctor_article_detail, name='detail'),
	url(r'^(?P<slug>[\w-]+)/edit/$',doctor_article_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/delete/$',doctor_article_delete,name='delete'),
	url(r'$',doctor_article_list, name='complain_list'),
	

	
	
]

templates/backup/bs_modalsignin.html
<div class="modal fade bs-example-modal-md" tabindex="-1" role="dialog">
		        				    <div class="modal-dialog modal-md" role="document">
			        				    <div class="modal-content">
			        				        <div class="modal-header">
				        				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        				        <h4 class="modal-title text-center">Login</h4>
				        				        <p class="text-center">Sign in and choose your service to have access to all our service.</p>
			        				        </div>
			        				        <div class="modal-body">
				        				      	<div class="row">
				        				      		<div class="col-sm-12 col-md-8 col-md-offset-2 text-center">
				        						        <form class="ulockd-login-form">
				        						        	<h3><span class="flaticon-lock"></span> Login</h3>
				        						        	<p>Enter username and password to login:</p>
				        						            <div class="form-group">
				            								    <input type="email" class="form-control" id="email" placeholder="Email">
				            								</div>
				            								<div class="form-group">
				            								    <input type="password" class="form-control" placeholder="Password">
				            								</div>
				        						            <button type="submit" class="btn btn-default ulockd-btn-thm2">Login to account</button>
				        						        </form>
				        				      		</div>
				        				      	</div>	
			        				        </div>
			        				        <!-- modal footer start here-->
			        				    </div>
		        				    </div>
		        				</div>

templates/backup/bs_modalsignup.html
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog">
									<div class="modal-dialog modal-lg" role="document">
			        				    <div class="modal-content">
			        				        <div class="modal-header">
				        				        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				        				        <h4 class="modal-title text-center" id="exampleModalLabel">Register</h4>
				        				        <p class="text-center">Sign in and choose your service to have access to all our service.</p>
			        				        </div>
			        				        <div class="modal-body">
				        				      	<div class="row">
				        				      		<div class="col-sm-12 col-md-8 col-md-offset-2">
				        						        <form class="ulockd-reg-form text-center row">
				        						        	<h3> <span class="flaticon-house-key"></span> Register</h3>
				        						        	<p>Join our community today:</p>
													        <div class="col-md-12">
					        						            <div class="form-group">
					            								    <input type="text" class="form-control" id="exampleInputNamexa" placeholder="First Name">
					            								</div>
													        </div>
													        <div class="col-md-12">
					        						            <div class="form-group">
					            								    <input type="text" class="form-control" id="exampleInputNamexb" placeholder="Last Name">
					            								</div>
													        </div>
													        <div class="col-md-12">
					        						            <div class="form-group">
					            								    <input type="email" class="form-control" id="exampleInputEmailx" placeholder="Email">
					            								</div>
													        </div>
													        <div class="col-md-12">
					            								<div class="form-group">
					            								    <input type="password" class="form-control" placeholder="Password">
					            								</div>
													        </div>
													        <div class="col-md-12">
					            								<div class="form-group">
					            								    <input type="password" class="form-control" placeholder="Repeat password">
					            								</div>
													        </div>
													        <div class="col-md-12">
					            								<div class="form-group text-center">
					            						        	<button type="submit" class="btn btn-default ulockd-btn-thm2">Sign Me Up</button>
					            								</div>
													        </div>
													        <div class="col-xxs-12 col-xs-5 col-sm-5 col-md-5">
													        	<a href="#" class="btn btn-lg btn-primary btn-block color-white">Facebook</a>
													        </div>
													        <div class="col-xxs-12 col-xs-2 col-sm-2 col-md-2">
													        	<a href="#">OR</a>
													        </div>
													        <div class="col-xxs-12 col-xs-5 col-sm-5 col-md-5">
													        	<a href="#" class="btn btn-lg btn-info btn-block color-white">Google</a>
													        </div>
				        						        </form>
				        				      		</div>
				        				      	</div>	
			        				        </div>
			        				        <!-- modal footer start here-->
			        				    </div>
									</div>
		        				</div>

templates/backup/sidebar_core.html
 <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
                            </span>Content</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span><a href="{% url 'dataadd:article' %}">Articles1</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-flash text-success"></span><a href="{% url 'dataadd:friends' %}">Friends</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-file text-info"></span><a href="{% url 'chat:chatpage' %}">Newsletters</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                                        <span class="badge">42</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Modules</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Invoices</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Shipments</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Tex</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                            </span>Account</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <a href="{% url 'account_change_password' %}">Change Password</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <a href="http://www.jquery2dotnet.com">Import/Export</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                                            Delete Account</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
                            </span>Reports</a>
                        </h4>
                    </div>
                    <div id="collapseFour" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        